# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python
python:
-   "2.7"
-   "3.3"
-   "3.4"
-   "3.5"
-   "3.6"
install:
-   pip install tox
script:
-   tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
notifications:
  email: false
